#!/usr/bin/env bash
# Regenerates the schema-derived documents from the migrations (so they cannot drift from the code):
#   docs/architecture/DATA_DICTIONARY.md, docs/architecture/ERD.md, docs/architecture/PERMISSION_MATRIX.md
#   ADA_TEST_PG_URL  admin connection URL (default postgresql://postgres:postgres@localhost:5432/postgres)
set -euo pipefail
cd "$(dirname "$0")/.."
ADMIN_URL="${ADA_TEST_PG_URL:-postgresql://postgres:postgres@localhost:5432/postgres}"
DB="ada_docs_$$"; URL="${ADMIN_URL%/*}/$DB"
psql_() { psql -X -q -v ON_ERROR_STOP=1 "$@"; }
psql_ "$ADMIN_URL" -c "create database $DB"
trap 'psql_ "$ADMIN_URL" -c "drop database if exists $DB" >/dev/null 2>&1' EXIT
psql_ "$URL" -f supabase/tests/00_supabase_shim.sql >/dev/null
for f in supabase/migrations/*.sql; do psql_ "$URL" -f "$f" >/dev/null; done

# ---- data dictionary -------------------------------------------------------------------------
{
cat <<'HDR'
# Data dictionary

_Generated by `scripts/gen-docs.sh` from the migrations. Do not edit by hand._

Each table lists its purpose and security classification (from the table comment), then every column.
Row-level security is enabled on every table; the policies are in the migrations and summarised in
[SECURITY.md](../SECURITY.md). Types such as `data_classification` are PostgreSQL enums.

HDR
psql_ "$URL" -Atq <<'SQL'
select string_agg(section, E'\n' order by relname) from (
  select c.relname,
    format(E'## `%s`\n\n%s\n\n| Column | Type | Required | Default | References |\n|---|---|---|---|---|\n%s\n',
      c.relname,
      coalesce(replace(obj_description(c.oid, 'pg_class'), 'Purpose: ', '**Purpose:** '), '_(no description)_'),
      (select string_agg(format('| `%s` | %s | %s | %s | %s |', a.attname, format_type(a.atttypid, a.atttypmod),
                case when a.attnotnull then 'yes' else 'no' end,
                coalesce(replace(pg_get_expr(d.adbin, d.adrelid), '|', '\|'), ''),
                coalesce((select format('`%s`', cl.relname) from pg_constraint k join pg_class cl on cl.oid = k.confrelid
                          where k.conrelid = c.oid and k.contype = 'f' and k.conkey = array[a.attnum]), '')), E'\n' order by a.attnum)
         from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
         where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)) as section
  from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind = 'r') t;
SQL
} > docs/architecture/DATA_DICTIONARY.md

# ---- ERD -----------------------------------------------------------------------------------------
{
cat <<'HDR'
# Entity relationship diagram

_Generated by `scripts/gen-docs.sh` from foreign keys in the migrations. Do not edit by hand._

Lines read "parent ||--o{ child": one parent row, many child rows. Optional links (nullable foreign keys) use `o|`.

```mermaid
erDiagram
HDR
psql_ "$URL" -Atq <<'SQL'
select distinct format('  %s %s--o{ %s : "%s"', p.relname,
         case when exists (select 1 from pg_attribute a where a.attrelid = k.conrelid and a.attnum = any (k.conkey) and not a.attnotnull) then 'o|' else '||' end,
         c.relname, (select a.attname from pg_attribute a where a.attrelid = k.conrelid and a.attnum = k.conkey[1]))
from pg_constraint k join pg_class c on c.oid = k.conrelid join pg_class p on p.oid = k.confrelid
where k.contype = 'f' and c.relnamespace = 'public'::regnamespace and p.relnamespace = 'public'::regnamespace and p.oid <> c.oid
order by 1;
SQL
echo '```'
echo
echo 'Not drawn: `staff.user_id -> auth.users` (the login provider), self-references (`divisions.parent_id`, `staff.deleted_by`), and `created_by`/`approved_by`-style audit links to `staff`.'
} > docs/architecture/ERD.md

# ---- permission matrix ---------------------------------------------------------------------------------------
node - <<'JS' > docs/architecture/PERMISSION_MATRIX.md
const fs = require('fs');
const split = (line) => { const o = []; let c = '', q = false; for (let i = 0; i < line.length; i++) { const ch = line[i];
  if (q) { if (ch === '"' && line[i + 1] === '"') { c += '"'; i++; } else if (ch === '"') q = false; else c += ch; }
  else if (ch === '"') q = true; else if (ch === ',') { o.push(c); c = ''; } else c += ch; } o.push(c); return o; };
const rows = fs.readFileSync('supabase/seed_data/permission_matrix.csv', 'utf8').trim().split('\n').map(split);
const h = rows.shift(); const roles = h.slice(3);
console.log('# Permission matrix\n\n_Generated from `supabase/seed_data/permission_matrix.csv`, which the test suite requires to equal the database. To change it, edit the CSV and ship a migration (`scripts/build-rbac-delta.mjs`)._\n');
console.log('A role assignment is organization-wide or scoped to one division. **Division Lead** and **Division Staff** are assigned per division; every other role is normally organization-wide. "x" = permission held.\n');
console.log(`| Permission | Class | ${roles.map((r) => r.replace(/_/g, ' ')).join(' | ')} |`);
console.log(`|---|---|${roles.map(() => ':-:').join('|')}|`);
for (const r of rows) console.log(`| \`${r[0]}\` — ${r[2]} | ${r[1]} | ${roles.map((_, i) => (r[3 + i] === 'x' ? 'x' : '')).join(' | ')} |`);
JS
echo "docs regenerated"
