-- 0004_rbac_seed: initial ADA organization, divisions, positions, permissions and roles.
-- Generated from supabase/seed_data/permission_matrix.csv by scripts/build-rbac-seed.mjs.

insert into organization (legal_name, trading_name, description)
values ('Andreas Digital Agency', 'ADA', 'Digital agency delivering web, technology, marketing, training, software and consulting services.');

insert into divisions (key, name, kind, sort_order, description) values
  ('management',     'Management',     'corporate', 10, 'Central executive and management function.'),
  ('administration', 'Administration', 'corporate', 20, 'Administrative records, documentation and internal coordination.'),
  ('finance',        'Finance',        'corporate', 30, 'Invoices, payments, expenses and financial reporting.'),
  ('web',            'ADA Web',        'service',   40, 'Web development and digital presence.'),
  ('tech',           'ADA Tech',       'service',   50, 'IT support, hardware, networking, CCTV, installations and maintenance.'),
  ('marketing',      'ADA Marketing',  'service',   60, 'Marketing and digital marketing.'),
  ('academy',        'ADA Academy',    'service',   70, 'Education, training and courses.'),
  ('software',       'ADA Software',   'service',   80, 'Software, portals, systems and application development.'),
  ('consulting',     'ADA Consulting', 'service',   90, 'Business and technology consulting.');

insert into positions (title, division_id, description)
select v.title, d.id, v.description
from (values
  ('Chief Executive',        'management',     'Head of ADA'),
  ('Administration Officer', 'administration', 'Administrative coordination'),
  ('Finance Officer',        'finance',        'Financial records'),
  ('Web Developer',          'web',            'Website design and development'),
  ('IT Technician',          'tech',           'IT support and installations'),
  ('Marketing Officer',      'marketing',      'Marketing delivery'),
  ('Academy Instructor',     'academy',        'Training delivery'),
  ('Software Developer',     'software',       'Application development'),
  ('Consultant',             'consulting',     'Advisory services')
) as v(title, division_key, description)
join divisions d on d.key = v.division_key;

insert into permissions (key, module, action, description, sensitivity) values
  ('staff.create', 'staff', 'create', 'Create staff records', 'internal'::data_classification),
  ('staff.update', 'staff', 'update', 'Edit staff records', 'internal'::data_classification),
  ('staff.delete', 'staff', 'delete', 'Soft-delete or restore staff records', 'restricted'::data_classification),
  ('staff.manage_accounts', 'staff', 'manage_accounts', 'Link logins and change account or employment status', 'restricted'::data_classification),
  ('hr.view', 'hr', 'view', 'Read sensitive HR information', 'confidential'::data_classification),
  ('hr.update', 'hr', 'update', 'Edit sensitive HR information', 'confidential'::data_classification),
  ('clients.view', 'clients', 'view', 'View clients', 'internal'::data_classification),
  ('clients.create', 'clients', 'create', 'Create clients', 'internal'::data_classification),
  ('clients.update', 'clients', 'update', 'Edit clients and link them to divisions', 'internal'::data_classification),
  ('clients.delete', 'clients', 'delete', 'Soft-delete or restore clients', 'restricted'::data_classification),
  ('clients.export', 'clients', 'export', 'Export client data', 'restricted'::data_classification),
  ('projects.view', 'projects', 'view', 'View projects', 'internal'::data_classification),
  ('projects.create', 'projects', 'create', 'Create projects', 'internal'::data_classification),
  ('projects.update', 'projects', 'update', 'Edit projects and add participating divisions', 'internal'::data_classification),
  ('projects.archive', 'projects', 'archive', 'Archive projects', 'internal'::data_classification),
  ('projects.delete', 'projects', 'delete', 'Soft-delete or restore projects', 'restricted'::data_classification),
  ('tasks.create', 'tasks', 'create', 'Create project tasks', 'internal'::data_classification),
  ('tasks.update', 'tasks', 'update', 'Update project tasks', 'internal'::data_classification),
  ('finance.view', 'finance', 'view', 'View financial records including project financials', 'confidential'::data_classification),
  ('finance.create', 'finance', 'create', 'Create and edit financial records', 'confidential'::data_classification),
  ('finance.approve', 'finance', 'approve', 'Approve financial records and workflows', 'confidential'::data_classification),
  ('finance.export', 'finance', 'export', 'Export financial data', 'confidential'::data_classification),
  ('roles.view', 'roles', 'view', 'View roles and the permission matrix', 'restricted'::data_classification),
  ('roles.administer', 'roles', 'administer', 'Create roles and assign or revoke permissions and role assignments', 'restricted'::data_classification),
  ('audit.view', 'audit', 'view', 'Read the audit log', 'restricted'::data_classification),
  ('reports.view', 'reports', 'view', 'View reports', 'internal'::data_classification),
  ('reports.generate', 'reports', 'generate', 'Generate reports', 'internal'::data_classification),
  ('reports.export', 'reports', 'export', 'Export reports', 'restricted'::data_classification),
  ('settings.update', 'settings', 'update', 'Edit organization settings divisions and positions', 'restricted'::data_classification),
  ('records.classify', 'records', 'classify', 'Mark records restricted or confidential', 'restricted'::data_classification),
  ('records.view_restricted', 'records', 'view_restricted', 'See records classified restricted', 'restricted'::data_classification),
  ('records.view_confidential', 'records', 'view_confidential', 'See records classified confidential', 'confidential'::data_classification),
  ('records.view_deleted', 'records', 'view_deleted', 'See soft-deleted records', 'restricted'::data_classification);

insert into roles (key, name, description, is_system) values
  ('ceo', 'Chief Executive', 'Full organizational authority. Holds every permission.', true),
  ('administration_officer', 'Administration Officer', 'Administrative records: staff, HR, clients; read-only on projects.', true),
  ('finance_officer', 'Finance Officer', 'Financial records and reporting. No HR, no audit, no role administration.', true),
  ('division_lead', 'Division Lead', 'Runs clients, projects and tasks within an assigned division (assign scoped to a division).', true),
  ('division_staff', 'Division Staff', 'Works on clients, projects and tasks within an assigned division (assign scoped to a division).', true),
  ('auditor', 'Auditor', 'Read-only oversight: audit log, access model and reports.', true);

insert into role_permissions (role_id, permission_id)
select r.id, p.id from (values
  ('ceo', 'staff.create'),
  ('administration_officer', 'staff.create'),
  ('ceo', 'staff.update'),
  ('administration_officer', 'staff.update'),
  ('ceo', 'staff.delete'),
  ('ceo', 'staff.manage_accounts'),
  ('ceo', 'hr.view'),
  ('administration_officer', 'hr.view'),
  ('ceo', 'hr.update'),
  ('administration_officer', 'hr.update'),
  ('ceo', 'clients.view'),
  ('administration_officer', 'clients.view'),
  ('finance_officer', 'clients.view'),
  ('division_lead', 'clients.view'),
  ('division_staff', 'clients.view'),
  ('ceo', 'clients.create'),
  ('administration_officer', 'clients.create'),
  ('division_lead', 'clients.create'),
  ('ceo', 'clients.update'),
  ('administration_officer', 'clients.update'),
  ('division_lead', 'clients.update'),
  ('ceo', 'clients.delete'),
  ('ceo', 'clients.export'),
  ('ceo', 'projects.view'),
  ('administration_officer', 'projects.view'),
  ('finance_officer', 'projects.view'),
  ('division_lead', 'projects.view'),
  ('division_staff', 'projects.view'),
  ('ceo', 'projects.create'),
  ('administration_officer', 'projects.create'),
  ('division_lead', 'projects.create'),
  ('ceo', 'projects.update'),
  ('administration_officer', 'projects.update'),
  ('division_lead', 'projects.update'),
  ('ceo', 'projects.archive'),
  ('division_lead', 'projects.archive'),
  ('ceo', 'projects.delete'),
  ('ceo', 'tasks.create'),
  ('administration_officer', 'tasks.create'),
  ('division_lead', 'tasks.create'),
  ('division_staff', 'tasks.create'),
  ('ceo', 'tasks.update'),
  ('administration_officer', 'tasks.update'),
  ('division_lead', 'tasks.update'),
  ('division_staff', 'tasks.update'),
  ('ceo', 'finance.view'),
  ('finance_officer', 'finance.view'),
  ('ceo', 'finance.create'),
  ('finance_officer', 'finance.create'),
  ('ceo', 'finance.approve'),
  ('ceo', 'finance.export'),
  ('finance_officer', 'finance.export'),
  ('ceo', 'roles.view'),
  ('administration_officer', 'roles.view'),
  ('auditor', 'roles.view'),
  ('ceo', 'roles.administer'),
  ('ceo', 'audit.view'),
  ('auditor', 'audit.view'),
  ('ceo', 'reports.view'),
  ('administration_officer', 'reports.view'),
  ('finance_officer', 'reports.view'),
  ('division_lead', 'reports.view'),
  ('auditor', 'reports.view'),
  ('ceo', 'reports.generate'),
  ('finance_officer', 'reports.generate'),
  ('ceo', 'reports.export'),
  ('finance_officer', 'reports.export'),
  ('ceo', 'settings.update'),
  ('ceo', 'records.classify'),
  ('administration_officer', 'records.classify'),
  ('ceo', 'records.view_restricted'),
  ('administration_officer', 'records.view_restricted'),
  ('auditor', 'records.view_restricted'),
  ('ceo', 'records.view_confidential'),
  ('ceo', 'records.view_deleted'),
  ('auditor', 'records.view_deleted')
) as v(role_key, permission_key)
join roles r on r.key = v.role_key
join permissions p on p.key = v.permission_key;
